name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
      - 'releases/v*'
  pull_request:
    paths-ignore:
      - '.github/xgo-releases.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Test
        uses: docker/bake-action@v5
        with:
          targets: test
      -
        name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
